Repository GSG-FC02/E-commerce-group2-project, pull requests merged in 2021-03, with the labels that each got.

#9 This is my code for the header-nav
  about.html
  images/header.jpg
  images/story.jpg
  index.css
  index.html
Labels: approved

#16 file structure correction
  images/header.jpg
  images/story.jpg
  index.css
Labels: in-progress

#10 show case
  index.css
  index.html
Labels: changes-request

#11 Our story section
  index.css
  index.html
Labels: approved

#17 add section our services and adjust Dimensions of 03.jpg
  img/service/03.jpg
  index.css
  index.html
Labels: approved

#12 Read me
  README.md
  about.html
Labels: approved

#18 add section projects
  index.css
  index.html
Labels: approved

#19 Edit Readme File
  README.md
Labels: approved

#14 creating Team section+styling it
  img/team/ibrahim.jpg
  img/team/ola.jpg
  index.css
  index.html
Labels: awaiting-review

#20 7 contactus footer
  index.css
  index.html
Labels: awaiting-review

#24 simple touch of project
  index.css
Labels: awaiting-review

#26 8 contact us
  contact.html
  index.css
  index.html
Labels: awaiting-review

#28 27 update readme file
  README.md
Labels: awaiting-review
